
["Config category"]
	#Set the client maximum memory warning threshold in MB. Choose a generous maximum with some additional over the required, e.g.recommended is 6000mb then set this to ~8000mb
	#Range: 2500 ~ 600000
	maximumClient = 9500
	#Disable the memory warnings, default = false
	disableWarnings = false
	#Set the server minimum memory warning threshold in MB. Choose the lowest value possible which keeps the pack playable.
	#Range: 2500 ~ 25000
	minimumServer = 4500
	#Set the server maximum memory warning threshold in MB. Choose a generous maximum with some additional over the required, e.g.recommended is 6000mb then set this to ~8000mb
	#Range: 2500 ~ 600000
	maximumServer = 9500
	#Set the help message for changing ram allocation
	helpfullinkmessage = "See <a href='https://minecrafthelp.co.uk/how-to-allocate-more-ram-to-minecraft-curseforge-overwolf/'>https://minecrafthelp.co.uk/how-to-allocate-more-ram-to-minecraft-curseforge-overwolf/</a> on how to change your memory settings."
	#Set the client minimum memory warning threshold in MB. Choose the lowest value possible which keeps the pack playable.
	#Range: 2500 ~ 25000
	minimumClient = 4500

